.\"	$OpenBSD$
.\"
.\" Copyright (c) 2017 Kenneth R Westerback <krw@openbsd.org>
.\" Copyright (c) 2005 Esben Norby <norby@openbsd.org>
.\" Copyright (c) 2004 Claudio Jeker <claudio@openbsd.org>
.\" Copyright (c) 2003, 2004 Henning Brauer <henning@openbsd.org>
.\" Copyright (c) 2002 Daniel Hartmeier <dhartmei@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: March 11 2015 $
.Dt NETCFGD.CONF 5
.Os
.Sh NAME
.Nm netcfgd.conf
.Nd Network Configuration Daemon configuration file
.Sh DESCRIPTION
.Nm
defines the policies implemented by
.Xr netcfgd 8 .
.Sh SECTIONS
The
.Nm
config file is divided into three sections.
.Bl -tag -width xxxx
.It Sy Macros
User-defined variables may be defined and used later, simplifying the
configuration file.
.It Sy Global Configuration
Zero or more
.Xr netcfgd 8
attibutes that define the overall policy for
.Xr netcfgd 8 .
.It Sy Interfaces
Lists of
.Xr netcfgd 8
attributes that define the policy relevant to the named network interface.
.El
.Pp
Additional configuration files can be included with the
.Ic include
keyword.
.Sh MACROS
Macros can be defined that will later be expanded in context.
Macro names must start with a letter, digit, or underscore,
and may contain any of those characters.
Macro names may not be reserved words (for example,
.Ic interface )
Macros are not expanded inside quotes.
.Sh GLOBAL CONFIGURATION
The global configuration section is a list of attribute specifications.
.Sh INTERFACES
An interface is a named list of attributes, specified with
.Bl -tag -width interface-name
.It interface Ar name { attribute list }
.El
.Pp
The possible
.Ic interface
attributes are
.Pp
.Bl -tag -width dhclient -compact
.It Sy dhclient
Accept proposals from dhclient.
.It Sy slaac
Accept proposals from slaac.
.It Sy static
Accept proposals from static configuration.
.El
.Sh EXAMPLE
.Bd -literal -offset indent
include "/etc/netcfgd.sub.conf"
dhcp="dhclient"
interface ix0 {
	$dhcp
	slaac
	static
}
.Ed
.Sh FILES
.Bl -tag -width "/etc/netcfgd.conf" -compact
.It Pa /etc/netcfgd.conf
.Xr netcfgd 8
configuration file
.El
.Sh SEE ALSO
.Xr netcfgd 8 ,
.Xr netcfgdfctl 8 ,
.Xr rc.conf.local 8
.Sh HISTORY
The
.Nm
file format first appeared in
.Ox X.Y .
